#pragma once

#define ENABLE_LOG							true
#define ENABLE_LOG_KEYPRESS					false
#define ENABLE_LOG_FOCUS					true	
#define ENABLE_LOG_MOUSEMOVEMENT			false
#define ENABLE_LOG_DELTATIME_AND_FPS		false
#define ENABLE_LOG_SPAWN_ENTITY_NOTICE		true
#define ENABLE_LOG_BREAK_ON_CRITICAL_ERROR	true
#define ENABLE_LOG_MOUSE_LOCK_MESSAGE		false
#define ENABLE_LOG_CAMERA_LOCATION_PRINT	false
#define ENABLE_LOG_COLLISION_MANIFOLD_PRINT	false
#define ENABLE_LOG_RIGIDBODY_DATA_PRINT		false
//#define ENABLE_LOG_

#define ENABLE_DRAW_OCTREE_OUTLINE false
#define ENABLE_DRAW_COLLIDERS_OUTLINE true
#define ENABLE_DRAW_WORLD_CHUNK_OUTLINE false